### ISSUE TITLE
refreshToken being returned as undefined

### ISSUE THREAD

**Issue by bananacity** [florianheinemann/passport-dropbox-oauth2#13]
Hi, I get the accesstoken succesfully but the refreshtoken is returned as undefined, what do I need to enable to get it correctly?
Also, is there documentation on how to use the refreshtoken to get a new accesstoken, or is this based on another library I need to look at documentation for to do that?

I tried adding tokenAccessType: 'offline', in the config but it's still returned as undefined

const passport = require('passport');
const DropboxStrategy = require('passport-dropbox-oauth2').Strategy;
const dotenv = require('dotenv');
const Dropbox = require('dropbox').Dropbox;
const fetch = require('node-fetch');
const User = require('../models/User');

// Load environment variables
dotenv.config();

// Configure Passport Dropbox OAuth strategy
passport.use(
  new DropboxStrategy(
    {
      apiVersion: '2',
      clientID: process.env.DROPBOX_APP_KEY,
      clientSecret: process.env.DROPBOX_APP_SECRET,
      callbackURL: process.env.DROPBOX_CALLBACK_URL,
      passReqToCallback: true,
    },
    async function (req, accessToken, refreshToken, profile, done) {
      console.log(refreshToken); // being returned as undefined for some reason

      const userId = req.query.state;
      try {
        const user = await User.findById(userId);
        if (user) {
          // save access token to account in database
          user.dropbox.accessToken = accessToken;
          // save refresh token too once i figure out how to get it
          user.dropbox.refreshToken = refreshToken;
          await user.save();
          done(null, user);
        } else {
          done(new Error('User not found'));
        }
      } catch (error) {
        done(error);
      }
    }
  )
);

const checkUser = async (accessToken) => {
  const dbx = new Dropbox({ accessToken, fetch });
  try {
    const user = await dbx.usersGetCurrentAccount();
    return user;
  } catch (error) {
    throw error;
  }
};

module.exports = { checkUser, passport };

**Comment by bananacity** [comment]
So to get a refresh token you have to do this to add token_access_type = 'offline' so that's appended in the URL, then dropbox API will return the refreshtoken.

`/ add ofline token type to dropbox passport
DropboxStrategy.prototype.authorizationParams = function(options){      
  options.token_access_type = 'offline';
  return options;
};

// Configure Passport Dropbox OAuth strategy
passport.use(
  new DropboxStrategy(
    {
      apiVersion: '2',
      clientID: process.env.DROPBOX_APP_KEY,
      clientSecret: process.env.DROPBOX_APP_SECRET,
      callbackURL: process.env.DROPBOX_CALLBACK_URL,
      passReqToCallback: true,
    },
    async function (req, accessToken, refreshToken, profile, done) {
      console.log(refreshToken);`

**Comment by mastercodelatam** [comment]
PLEASE ADD THIS INFO A DOC
--------------------------- browser index --------------------------------------
how to implement offline token in dropbox OAUTH ?
¿Cómo implementar un token sin conexión en Dropbox OAUTH?
--------------------------- browser index --------------------------------------
